### ISSUE TITLE
Error in X[, rownames(Sigma)] : subscript out of bounds

### ISSUE THREAD

**Issue by bvasiles** [jslefche/rsquared.glmm#6] opened 2015-08-13 17:20 UTC
This fails with `Error in X[, rownames(Sigma)] : subscript out of bounds`:

```
library(lme4)
m = lmer(formula, data=mydata, REML=FALSE)
rsquared.glmm(m)
```

**Comment by jslefche** [comment] 2015-08-18 21:04
Cannot reproduce. Can you provide an example?

Also does your model run with the code here: https://github.com/jslefche/piecewiseSEM/blob/master/R/sem.model.fits.R

**Comment by aenrichus** [comment] 2015-10-19 14:49
I have tried both and get the same error, except with an additional parameter in the sem.model.fits version from the package with a Large lmerMod. 

Error in X[, rownames(Sigma), drop = FALSE] : subscript out of bounds

**Comment by jslefche** [comment] 2015-10-19 20:12
Can you provide a reproducible example?

**Comment by aenrichus** [comment] 2015-10-19 22:41
The below is the model I am working with, but it could be hard for you to reproduce without the data. Let me know if emailing that to you would help.

m05 <- lmer(rt ~ order + type + word + prt*pkey + art.eff + pde.eff + swe.eff + 
                         (1 + order + spell.eff | id) + (1 | stim), data, REML = F)

sem.model.fits(m05)

**Comment by aenrichus** [comment] 2015-10-20 14:25
Attempted on another computer. No problems on that one. Odd.

Thanks for the package! Very useful!

**Comment by jslefche** [comment] 2015-10-21 13:43
Not sure what the root problem was (perhaps a memory issue?) but since the @aenrichus was able to run the function on a different computer suggests that the bug has been fixed in more recent versions. So going to close this one..

**Closed as completed by jslefche** 2015-10-21 13:43 UTC

**Comment by mhlinder** [comment] 2017-04-27 03:08
In case anyone else has this problem (my experience was on `piecewiseSEM`, but this issue was the top result):

I had a model estimated with `lmer` (`lme4`), and received this error. Estimating the same model again with `lme` (`nlme`) eventually led to the culprit: a random effect that did not correspond to any fixed effect:

```
> sem.model.fits(m0)
Error in Z %*% getVarCov(model) : non-conformable arguments
In addition: Warning message:
In FUN(X[[i]], ...) :
  Random slopes not present as fixed effects. This artificially inflates calculations of conditional R2. Respecify fixed structure!
```

Adding the fixed effect fixed the problem.
